name: New Relic Fluent Bit Output Plugin - Pull Request

on: [pull_request]

jobs:
  ci:
    name: Continuous Integration pipeline
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: go test ./...

      - name: Build project
        run: make all

